---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-codeartifact-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - codeartifact.services.k8s.aws
  resources:
  - domains
  - packagegroups
  verbs:
  - get
  - list
  - watch
